### ISSUE TITLE
Error Building SDK in Visual Studio for ARM64

### ISSUE THREAD

**Issue by mscherotter** [mixer/interactive-cpp#102]
Building the SDK for ARM64 in Visual Studio 2017 triggers a warning from the rapidjson.h library.  Please advise on how to address this.

1>pch.cpp
1>interactivity.cpp
1>d:\source\repos\interactive-cpp\source\internal\rapidjson\rapidjson.h(244): fatal error C1189: #error:  Unknown machine endianess detected. User needs to define RAPIDJSON_ENDIAN.

Thanks, 
Michael

**Comment by JoshSnider** [comment]
ARM isn't a supported platform but could work, have you tried defining RAPIDJSON_ENDIAN as detailed here? http://rapidjson.org/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#gaba2445f582142cf918e74c2d22d1aa07

**Comment by mscherotter** [comment]
I got it to build by adding 
#  elif defined(_M_ARM64) // Microsoft ARM64
#    define RAPIDJSON_ENDIAN RAPIDJSON_LITTLEENDIAN
#  else
but I still don't have a device to test with.
I'll report back when I do.

**Comment by JoshSnider** [comment]
Sounds good, if it works feel free to send a pull request.
