### ISSUE TITLE
Xbox sample unusable - fails activation request

### ISSUE THREAD

**Issue by jimleedham** [mixer/interactive-cpp#24]
Hi, trying to get started with the Xbox sample. Code is compiled and s_interactiveVersion set to my project's VersionID. My xbox is in developer mode, has latest recovery installed (and I've tried with and without sandbox set to XDKS.1). However every time I try to launch I get:

![failed-activation](https://user-images.githubusercontent.com/30353869/28480063-feec5676-6e2c-11e7-8ffc-d87f45d98dcc.png)

and on the devkit I see:

![172 16 1 140_image_77](https://user-images.githubusercontent.com/30353869/28480095-27eabe5a-6e2d-11e7-9bb9-c2876dd60c72.png)

and this is the Output:
Starting Title...
Title failed to start
Error trying to debug Title

Thoughts?

**Comment by payzer** [comment]
Thank you for filing this issue, we are investigating.

**Comment by payzer** [comment]
Unfortunately we weren't able to repro (I also have the latest recovery and XDKS.1 as my sandbox). Setting your Sandbox to XDKS.1 is the right sandbox. The error result says "activation failed". Does this happen for all games or just the sample?

**Comment by jimleedham** [comment]
Ahh no, my apologies, looks like it's happening for all samples, so it must be something wrong with my kit's setup (or our network). I'll do some more investigating

**Comment by payzer** [comment]
No worries. I'm sorry to hear about the devkit activation issues. I'll close this, but don't hesitate to reach out for help if you cannot figure out what's going on with your devkit :)

**Comment by jimleedham** [comment]
Thanks, just tried another devkit and it worked, other one probably needs a reset.
