### ISSUE TITLE
Incorrect URL in documentation

### ISSUE THREAD

**Issue by triverske** [mixer/interactive-cpp#29]
I hope this is the right place to report this. There's a small misprint under the "Choose a SDK" section in the [interactive reference](https://dev.mixer.com/reference/interactive/index.html) 

The Github link goes to "https://github.com/mixer/interactive-sdk-cpp" 
when it should go to "https://github.com/mixer/interactive-cpp/"

**Comment by payzer** [comment]
Thank you for reporting the issue! I checked and it looks like one of our engineers has fixed the link. Thank you again for reporting it!
