### ISSUE TITLE
v2 interactive_control_trigger_cooldown seems to only work once per session per button

### ISSUE THREAD

**Issue by jsyarrow** [mixer/interactive-cpp#42]
Test project with multiple buttons where the client responds to a button press by triggering a 5s cooldown on the pressed button.  Each button runs its cooldown the first time it is pressed.  Subsequence presses of the same button do not trigger a cooldown (as observed at mixer.com).  The client does get an onControlUpdate message from the service in response to the cooldown request even when no cooldown occurs, but the value of the cooldown field remains unchanged after the first successful cooldown.

At a guess the problem is a missing seq field on the outgoing message.

**Comment by JoshSnider** [comment]
@jsyarrow I'm not able to reproduce this one. Can you send me a version ID/share code that exhibits this behavior?
