### ISSUE TITLE
v2 label textSize property has unexpected type

### ISSUE THREAD

**Issue by jsyarrow** [mixer/interactive-cpp#43]
`interactive_control_get_property_int(MySession, "mylabel", "textSize", &outTextSize)` returns `MIXER_ERROR_INVALID_PROPERTY_TYPE`.  The property appears to be treated as a string internally, despite holding an integer value (36 in my case).

**Comment by JoshSnider** [comment]
This is by design, the textSize property supports all CSS font-size value types, e.g. "5px", "150%", "large", etc.
