### ISSUE TITLE
Crash in interactive_get_user

### ISSUE THREAD

**Issue by JoshSnider** [mixer/interactive-cpp#89]
I have encountered a crash when calling interactive_get_user.
The detail is as follows:
  File   : interactive_session.cpp(898)
  Source : user.avatarUrl = responseDoc["avatarUrl"].GetString();
  Message: Expression: IsString()

It looks data_.f.flags is 0 and fails on RAPIDJSON_ASSERT(IsString()).

The code works fine on Xbox One, but it crashes on PC.

**Comment by connor4312** [comment]
The avatar URL may be null -- could that cause the error you're seeing?

**Comment by JoshSnider** [comment]
Yeah I believe a null check before attempting to get the string will fix this.

**Comment by JoshSnider** [comment]
Fixed with: cff5898bf3d553757193054afae6044674481973
